-- ============================================================
-- TruePeopleSearch 客户精准数据视图与字段迁移脚本
-- 兼容 Navicat 视图浏览与 1键 CSV 导出
-- ============================================================

USE people_search;

-- 1. 为主表补齐中文报表与竞品对标字段
ALTER TABLE persons
    ADD COLUMN IF NOT EXISTS first_name         VARCHAR(100) NULL COMMENT '名',
    ADD COLUMN IF NOT EXISTS middle_name        VARCHAR(100) NULL COMMENT '中间名',
    ADD COLUMN IF NOT EXISTS last_name          VARCHAR(100) NULL COMMENT '姓',
    ADD COLUMN IF NOT EXISTS gender             VARCHAR(10) DEFAULT '未知' COMMENT '性别',
    ADD COLUMN IF NOT EXISTS primary_phone      VARCHAR(30) NULL COMMENT '当前电话(优先无线手机号)',
    ADD COLUMN IF NOT EXISTS primary_phone_type VARCHAR(30) NULL COMMENT '当前电话类型(Wireless/Landline/Voip)',
    ADD COLUMN IF NOT EXISTS current_address    VARCHAR(500) NULL COMMENT '当前完整地址',
    ADD COLUMN IF NOT EXISTS address_duration   VARCHAR(100) NULL COMMENT '当前地址居住时长',
    ADD COLUMN IF NOT EXISTS all_phones         TEXT NULL COMMENT '全部电话列表(逗号分隔)',
    ADD COLUMN IF NOT EXISTS wireless_phone_1   VARCHAR(30) NULL COMMENT '移动号码1',
    ADD COLUMN IF NOT EXISTS wireless_phone_2   VARCHAR(30) NULL COMMENT '移动号码2',
    ADD COLUMN IF NOT EXISTS wireless_phone_3   VARCHAR(30) NULL COMMENT '移动号码3';

-- 2. 保留既有记录。报告资格通过下面的视图过滤，不自动删除历史数据。

-- 3. 创建与客户 Navicat 完全一致的中文视图 [人物主表]
CREATE OR REPLACE VIEW 人物主表 AS
SELECT
    p.person_id AS `人物ID`,
    p.full_name AS `全名`,
    p.gender AS `性别`,
    p.age AS `年龄`,
    COALESCE(CASE WHEN (COALESCE(p.primary_phone, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.primary_phone, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') AND LOWER(TRIM(COALESCE(p.primary_phone_type, ''))) IN ('wireless', 'landline', 'landline/services') THEN p.primary_phone END, CASE WHEN (COALESCE(p.wireless_phone_1, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_1, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') THEN p.wireless_phone_1 END, CASE WHEN (COALESCE(p.wireless_phone_2, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_2, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') THEN p.wireless_phone_2 END, CASE WHEN (COALESCE(p.wireless_phone_3, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_3, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') THEN p.wireless_phone_3 END, (SELECT visible_phone.phone_number FROM phone_numbers visible_phone WHERE visible_phone.person_id = p.person_id AND (COALESCE(visible_phone.phone_number, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(visible_phone.phone_number, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') AND LOWER(TRIM(COALESCE(visible_phone.line_type, ''))) IN ('wireless', 'landline', 'landline/services') ORDER BY visible_phone.is_primary DESC, visible_phone.phone_number LIMIT 1)) AS `当前电话`,
    COALESCE(CASE WHEN (COALESCE(p.primary_phone, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.primary_phone, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') AND LOWER(TRIM(COALESCE(p.primary_phone_type, ''))) IN ('wireless', 'landline', 'landline/services') THEN p.primary_phone_type END, CASE WHEN (COALESCE(p.wireless_phone_1, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_1, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') THEN 'Wireless' END, CASE WHEN (COALESCE(p.wireless_phone_2, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_2, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') THEN 'Wireless' END, CASE WHEN (COALESCE(p.wireless_phone_3, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_3, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') THEN 'Wireless' END, (SELECT visible_phone.line_type FROM phone_numbers visible_phone WHERE visible_phone.person_id = p.person_id AND (COALESCE(visible_phone.phone_number, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(visible_phone.phone_number, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') AND LOWER(TRIM(COALESCE(visible_phone.line_type, ''))) IN ('wireless', 'landline', 'landline/services') ORDER BY visible_phone.is_primary DESC, visible_phone.phone_number LIMIT 1)) AS `当前电话类型`,
    p.current_address AS `当前地址`,
    p.address_duration AS `当前地址时长`,
    p.last_name AS `姓`,
    p.first_name AS `名`,
    p.middle_name AS `中间名`,
    CONCAT_WS(', ', CASE WHEN (COALESCE(p.primary_phone, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.primary_phone, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') AND LOWER(TRIM(COALESCE(p.primary_phone_type, ''))) IN ('wireless', 'landline', 'landline/services') THEN CONCAT(p.primary_phone, ' (', p.primary_phone_type, ')') END, CASE WHEN (COALESCE(p.wireless_phone_1, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_1, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') THEN CONCAT(p.wireless_phone_1, ' (Wireless)') END, CASE WHEN (COALESCE(p.wireless_phone_2, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_2, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') THEN CONCAT(p.wireless_phone_2, ' (Wireless)') END, CASE WHEN (COALESCE(p.wireless_phone_3, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_3, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') THEN CONCAT(p.wireless_phone_3, ' (Wireless)') END, (SELECT GROUP_CONCAT(DISTINCT CONCAT(visible_phone.phone_number, ' (', visible_phone.line_type, ')')) FROM phone_numbers visible_phone WHERE visible_phone.person_id = p.person_id AND (COALESCE(visible_phone.phone_number, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(visible_phone.phone_number, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') AND LOWER(TRIM(COALESCE(visible_phone.line_type, ''))) IN ('wireless', 'landline', 'landline/services'))) AS `电话列表`,
    CASE WHEN (COALESCE(p.wireless_phone_1, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_1, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') THEN p.wireless_phone_1 END AS `移动号码1`,
    CASE WHEN (COALESCE(p.wireless_phone_2, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_2, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') THEN p.wireless_phone_2 END AS `移动号码2`,
    CASE WHEN (COALESCE(p.wireless_phone_3, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_3, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') THEN p.wireless_phone_3 END AS `移动号码3`
FROM persons p
WHERE (((COALESCE(p.primary_phone, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.primary_phone, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') AND LOWER(TRIM(COALESCE(p.primary_phone_type, ''))) IN ('wireless', 'landline', 'landline/services')) OR (COALESCE(p.wireless_phone_1, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_1, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') OR (COALESCE(p.wireless_phone_2, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_2, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') OR (COALESCE(p.wireless_phone_3, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(p.wireless_phone_3, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') OR EXISTS (SELECT 1 FROM phone_numbers visible_phone WHERE visible_phone.person_id = p.person_id AND (COALESCE(visible_phone.phone_number, '') REGEXP '^[+() .-]*(1[+() .-]*)?[2-9][+() .-]*[0-9][+() .-]*[0-9][+() .-]*[2-9][+() .-]*([0-9][+() .-]*){6}$' AND COALESCE(visible_phone.phone_number, '') NOT REGEXP '^[+() .-]*(1[+() .-]*)?((2[+() .-]*){10}|(3[+() .-]*){10}|(4[+() .-]*){10}|(5[+() .-]*){10}|(6[+() .-]*){10}|(7[+() .-]*){10}|(8[+() .-]*){10}|(9[+() .-]*){10})$') AND LOWER(TRIM(COALESCE(visible_phone.line_type, ''))) IN ('wireless', 'landline', 'landline/services')));
